### PR TITLE
Amanda/small fixes

### PR DESCRIPTION
**Pull request by acholyn**
- fixes not flying to currentlocation on each gps button click
- fixed loader to only show with new map

### CODE REVIEW

**Comment by tcouch** [comment]
Looks like this will be easier to review once the other PRs have been merged.

**Review by MarcosMoreu — APPROVED** [review]

**Comment by MarcosMoreu** [comment]
> Looks like this will be easier to review once the other PRs have been merged.

Shall we merge this to main and then test the app before deploying it?

**Comment by acholyn** [comment]
I've deployed on staging to test before merge

**Comment by acholyn** [comment]
on my android doing the export no longer triggers the map

**Pull request merged**
